# -*- coding: utf-8 -*-
"""task1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sfZQEwtb38clmj7KnwnEIqgqYioMLV9C
"""

import matplotlib.pyplot as plt
import numpy as np

# Generate sample age data
np.random.seed(0)
ages = np.random.randint(1, 100, size=1000)

# Create the histogram
plt.figure(figsize=(10, 6))
plt.hist(ages, bins=20, edgecolor='black', alpha=0.7)
plt.xlabel('Age')
plt.ylabel('Frequency')
plt.title('Distribution of Ages in a Population')
plt.grid(axis='y', alpha=0.75)
plt.show()